var namespacemc =
[
    [ "aux", "namespacemc_1_1aux.html", "namespacemc_1_1aux" ],
    [ "err", "namespacemc_1_1err.html", null ],
    [ "io", "namespacemc_1_1io.html", "namespacemc_1_1io" ],
    [ "ipc", "namespacemc_1_1ipc.html", "namespacemc_1_1ipc" ],
    [ "log", "namespacemc_1_1log.html", null ],
    [ "none", "namespacemc_1_1none.html", "namespacemc_1_1none" ],
    [ "proto", "namespacemc_1_1proto.html", "namespacemc_1_1proto" ],
    [ "thread", "namespacemc_1_1thread.html", "namespacemc_1_1thread" ],
    [ "result_t", "classmc_1_1result__t.html", "classmc_1_1result__t" ],
    [ "client_config_t", "classmc_1_1client__config__t.html", "classmc_1_1client__config__t" ],
    [ "client_template_t", "classmc_1_1client__template__t.html", "classmc_1_1client__template__t" ],
    [ "error_t", "classmc_1_1error__t.html", "classmc_1_1error__t" ],
    [ "out_of_servers_t", "classmc_1_1out__of__servers__t.html", "classmc_1_1out__of__servers__t" ],
    [ "city_t", "classmc_1_1city__t.html", "classmc_1_1city__t" ],
    [ "jenkins_t", "classmc_1_1jenkins__t.html", "classmc_1_1jenkins__t" ],
    [ "murmur3_t", "classmc_1_1murmur3__t.html", "classmc_1_1murmur3__t" ],
    [ "spooky_t", "classmc_1_1spooky__t.html", "classmc_1_1spooky__t" ],
    [ "scope_guard_t", "classmc_1_1scope__guard__t.html", "classmc_1_1scope__guard__t" ],
    [ "consistent_hashing_pool_config_t", "classmc_1_1consistent__hashing__pool__config__t.html", "classmc_1_1consistent__hashing__pool__config__t" ],
    [ "consistent_hashing_pool_base_t", "classmc_1_1consistent__hashing__pool__base__t.html", "classmc_1_1consistent__hashing__pool__base__t" ],
    [ "consistent_hashing_pool_const_iterator", "classmc_1_1consistent__hashing__pool__const__iterator.html", "classmc_1_1consistent__hashing__pool__const__iterator" ],
    [ "consistent_hashing_pool_t", "classmc_1_1consistent__hashing__pool__t.html", "classmc_1_1consistent__hashing__pool__t" ],
    [ "mod_pool_base_t", "classmc_1_1mod__pool__base__t.html", "classmc_1_1mod__pool__base__t" ],
    [ "mod_pool_const_iterator", "classmc_1_1mod__pool__const__iterator.html", "classmc_1_1mod__pool__const__iterator" ],
    [ "mod_pool_t", "classmc_1_1mod__pool__t.html", "classmc_1_1mod__pool__t" ],
    [ "server_proxies_t", "classmc_1_1server__proxies__t.html", "classmc_1_1server__proxies__t" ],
    [ "server_proxy_config_t", "classmc_1_1server__proxy__config__t.html", "classmc_1_1server__proxy__config__t" ],
    [ "server_proxy_t", "classmc_1_1server__proxy__t.html", "classmc_1_1server__proxy__t" ],
    [ "SpookyHash", "classmc_1_1SpookyHash.html", "classmc_1_1SpookyHash" ],
    [ "Initializer_t", "classmc_1_1Initializer__t.html", "classmc_1_1Initializer__t" ]
];